#!/usr/bin/env bash
set -Eeuo pipefail

trap 'printf "\nSetup failed at line %s.\n" "$LINENO" >&2' ERR

QUARTO_VERSION="${QUARTO_VERSION:-1.10.15}"
PYTHON_COMMAND="${PYTHON_COMMAND:-python3}"

require_command() {
    local command_name="$1"
    if ! command -v "$command_name" >/dev/null 2>&1; then
        printf 'Required command is missing: %s\n' "$command_name" >&2
        exit 1
    fi
}

append_local_exclude() {
    local pattern="$1"
    if ! grep -qxF "$pattern" .git/info/exclude 2>/dev/null; then
        printf '%s\n' "$pattern" >> .git/info/exclude
    fi
}

require_command git
require_command "$PYTHON_COMMAND"
require_command node

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$REPO_ROOT" ]]; then
    printf 'Run this script from inside the Technological Education Resources Git repository.\n' >&2
    exit 1
fi
cd "$REPO_ROOT"

if [[ ! -f site/_quarto.yml ]]; then
    printf 'Expected Quarto project not found: %s/site/_quarto.yml\n' "$REPO_ROOT" >&2
    exit 1
fi

QUARTO_BIN="${QUARTO_BIN:-$HOME/opt/quarto-$QUARTO_VERSION/bin/quarto}"
if [[ ! -x "$QUARTO_BIN" ]]; then
    printf 'Pinned Quarto executable is missing:\n  %s\n' "$QUARTO_BIN" >&2
    printf 'Install Quarto %s under ~/opt or set QUARTO_BIN.\n' "$QUARTO_VERSION" >&2
    exit 1
fi

ACTUAL_QUARTO_VERSION="$($QUARTO_BIN --version | head -n 1)"
if [[ "$ACTUAL_QUARTO_VERSION" != "$QUARTO_VERSION" ]]; then
    printf 'Expected Quarto %s, found %s at %s\n' \
        "$QUARTO_VERSION" "$ACTUAL_QUARTO_VERSION" "$QUARTO_BIN" >&2
    exit 1
fi

VENV_DIR="$REPO_ROOT/.venv"
ENV_FILE="$REPO_ROOT/.bs-server-env.sh"

append_local_exclude '.venv/'
append_local_exclude '.bs-server-env.sh'
append_local_exclude 'site/_publish.yml'

printf 'Repository: %s\n' "$REPO_ROOT"
printf 'Quarto:    %s\n' "$QUARTO_BIN"
printf 'Python:    %s\n' "$(command -v "$PYTHON_COMMAND")"
printf 'Node:      %s\n' "$(command -v node)"
printf '\n'

if [[ ! -x "$VENV_DIR/bin/python" ]]; then
    printf 'Creating repository-local Python environment...\n'
    "$PYTHON_COMMAND" -m venv "$VENV_DIR"
else
    printf 'Using existing repository-local Python environment.\n'
fi

printf 'Installing Python dependencies...\n'
"$VENV_DIR/bin/python" -m pip install --upgrade pip
"$VENV_DIR/bin/python" -m pip install -r requirements.txt
"$VENV_DIR/bin/python" -m pip check

cat > "$ENV_FILE" <<EOF_ENV
# Generated by scripts/bs-setup-server-environment.sh
export PATH="$VENV_DIR/bin:$HOME/opt/quarto-$QUARTO_VERSION/bin:\$PATH"
export QUARTO_BIN="$QUARTO_BIN"
EOF_ENV
chmod 600 "$ENV_FILE"

printf 'Running Commons source checks...\n'
PATH="$VENV_DIR/bin:$HOME/opt/quarto-$QUARTO_VERSION/bin:$PATH" \
QUARTO_BIN="$QUARTO_BIN" \
    "$VENV_DIR/bin/python" scripts/check_commons.py

printf '\nEnvironment setup passed.\n'
printf 'Future builds can run with:\n  bash scripts/bs-build-and-publish.sh\n'
printf 'Optional interactive Bash environment:\n  source %s\n' "$ENV_FILE"
